### PR TITLE
Layout, colors and visual hierarchy

### PR DESCRIPTION
**Pull request by alvp01**
### In this feature brach:
- I will make the layout for the website.
- I will put some colors to simulate the smashing magazine color hierarchy.
- I will simulate the smashing magazine visual hierarchy

### CODE REVIEW

**Comment by MarioDena** [comment]
## Project under review by Mario Enrique Delgado Naranjo

**Comment by alvp01** [comment]
> Hello! Great work on your project! I can see you dedicated a great deal of time and effort! 👏 👏
> 
> However there are some changes required for this project to be approved!
> 
> ## Required Changes
> * [ ]  The body of your project has a margin, please remove it. The original page uses 100% of the view-port (there is no white margin around the red colored background).
> * [ ]  Your project shows a horizontal scrollbar, please be sure that either your HTML fits on 100% of the page or if it exceeds it (by 1px or 2 caused by different browsers) hide the horizontal scrollbar.
> 
> img
> 
> * [ ]  Please remove all the comments on your code. I know they are there to keep track of your coding sections however all your projects must not contain comments. Think of this as not something you did wrong but as a mandatory requirement from a client. (This will also force you to use really descriptive names for your classes and ID's)
> * [ ]  Remember to keep your code DRY (Don't repeat yourself) There are a lot of repeated rules on your CSS file, for example the rule `width: 100%` and `height: 100%` are repeated over 30 times. Also `display: flex` is overused. (Keep in mid I'm referring to repetition on your code, not on missuses as your rules are correct) You can read this article if you need further guidance. https://speckyboy.com/good-bad-css-practices/
> * [ ]  Lastly remember to give your PR a descriptive and meaningful description.
>   img2
> 
> ## Optional Changes
> * [ ]  To avoid the margin problems you could use a CSS Reset file I recommend you reading about it and googling to see if that approach fit your working style. **This is [OPTIONAL]**
> * [ ]  One way to solve repetition is to create base classes to add on to your HTML for example
> 
> ```css
> .full-space{
> width: 100%
> height: 100%
> }
> ```
> 
> Then add that class to your HTML apart from other styling. This is of course just 1 way to do it. **This is [OPTIONAL]**
> 
> I encourage you to find your own solutions and again congratulations on your project it was almost ready. 🏅
> After making the aforementioned changes please resubmit your code for another review. ❕
> 
> ## Code Review by Mario Enrique Delgado Naranjo

Thank you for you time and work. The suggestion of the comments within the code intrigues me. In fact, you are the first TSE that tells me to delete the comments in the code, I will do it anyways.

Also, I'm having problems finding a solution for the horizontal bar. Any suggestions that could help in that regard? 

Thanks again,  for your work.

**Comment by MarioDena** [comment]
Hello! Yeah it happens to me too the first time I was asked to remove the comments! 😄 

About the horizontal bar you could both try a CSS reset or simply set the display to the horizontal bar to hidden. 

Cheers!!

**Comment by alvp01** [comment]
> ## Status: Require changes 🔴
> Hi, @alvp01 you did great fixing the changes recommended by the previous reviewer 👍 , However, we failed to implement 2 of the comments requested by the previous reviewer. Find comments below:
> 
> * We were asked by the previous reviewer to avoid repeating code. We still have ` width:100%, height:100%, and display: flex` . I suggest we use this approach, for example =>` .one, .two, .three, .four { width:100% }`. Let us find the classes with the same properties and group them nicely.
> * You did not edit the PR as pointed out in the first review. We can edit the PR by clicking on the `...` next to the emoji at the far right of the PR.
> 
> Kindly make these changes and submit another code review 😃
> _Happy coding_ 👨‍💻
> @slack on Daniel Larbi Addo

I changed a lot of the code, in fact I created classes to avoid overusing of some rules.

**Comment by addod19** [comment]
> > ## Status: Require changes 🔴
> > Hi, @alvp01 you did great fixing the changes recommended by the previous reviewer 👍 , However, we failed to implement 2 of the comments requested by the previous reviewer. Find comments below:
> > 
> > * We were asked by the previous reviewer to avoid repeating code. We still have ` width:100%, height:100%, and display: flex` . I suggest we use this approach, for example =>` .one, .two, .three, .four { width:100% }`. Let us find the classes with the same properties and group them nicely.
> > * You did not edit the PR as pointed out in the first review. We can edit the PR by clicking on the `...` next to the emoji at the far right of the PR.
> > 
> > Kindly make these changes and submit another code review 😃
> > _Happy coding_ 👨‍💻
> > @slack on Daniel Larbi Addo
> 
> I changed a lot of the code, in fact I created classes to avoid overusing of some rules.

How about you try to edit the PR.

**Comment by alvp01** [comment]
> > > ## Status: Require changes 🔴
> > > Hi, @alvp01 you did great fixing the changes recommended by the previous reviewer 👍 , However, we failed to implement 2 of the comments requested by the previous reviewer. Find comments below:
> > > 
> > > * We were asked by the previous reviewer to avoid repeating code. We still have ` width:100%, height:100%, and display: flex` . I suggest we use this approach, for example =>` .one, .two, .three, .four { width:100% }`. Let us find the classes with the same properties and group them nicely.
> > > * You did not edit the PR as pointed out in the first review. We can edit the PR by clicking on the `...` next to the emoji at the far right of the PR.
> > > 
> > > Kindly make these changes and submit another code review 😃
> > > _Happy coding_ 👨‍💻
> > > @slack on Daniel Larbi Addo
> > 
> > 
> > I changed a lot of the code, in fact I created classes to avoid overusing of some rules.
> 
> How about you try to edit the PR.

I changed the PR name and deleted most of the flex rules.

**Comment by uryelah** [comment]
### Project under review by Sarah Chamorro

**Comment by uryelah** [comment]
Hello **Abel Lavieri**, I'm Sarah, your reviewer for this PR .

You did a good job implementing all but one change. 

Take a couple of minutes to implement the last required change and your project should be good to go. 🙏 

-------

### Required Change

- [ ]  The **PR must have both a descriptive title and description**. 
Please follow the model of a professional pull request message[ found here.](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

69548761-3a8d3600-0f98-11ea-9f19-14da361c12e2

-------

**Kindly implement the changes above and request a new code review.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by alvp01** [comment]
> Hello **Abel Lavieri**, I'm Sarah, your reviewer for this PR . 👩‍🚀
> 
> You did a good job implementing all but one change.
> 
> Take a couple of minutes to implement the required changes and your project should be good to go. 🙏
> 
> ### Required Change
> * [ ]   The **PR must have both a descriptive title and description**.
>   Please follow the model of a professional pull request message[ found here.](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
> 
> 69548761-3a8d3600-0f98-11ea-9f19-14da361c12e2
> 
> * [ ]  Make sure your html passes the[ validator.](https://validator.w3.org/nu/)
> 
> validation_requirement
> 
> _Optional changes_
> 
> * [ ]  [OPTIONAL] Please make the links and lists all black and white or in gray. The idea of the design tear down is to understand the visual weight of the elements and a touch of color in a mostly grey area calls a lot of attention to itself, defying the objective of the exercise.
> 
> Screenshot_2020-02-28 Smashing Magazine Tear Design
> 
> **Kindly implement the changes above and request a new code review.**
> 
> Cheers and Happy coding!👏👏👏
> 
> Code review by **Sarah Uryelah Silva Chamorro**
> 
> (Feel free to contact me on slack by the handle of **sarah** if you have any additional question)

I made the changes required.

**Comment by majovanilla** [comment]
### Project under review by Maria Reyes

**Comment by majovanilla** [comment]
Hey @alvp01 

## Nice job implementing the required changes :clap: 

However, I see you still have some warnings on your HTML file that you should work on.
Screenshot from 2020-02-28 18-13-10


That's the only change required before being able to approve the request.

### STATUS: changes required :warning: 

Code reviewer: Maria Reyes. Find me on slack like @majo

**Comment by alvp01** [comment]
> Hey @alvp01
> 
> ## Nice job implementing the required changes 👏
> However, I see you still have some warnings on your HTML file that you should work on.
> Screenshot from 2020-02-28 18-13-10
> 
> That's the only change required before being able to approve the request.
> 
> ### STATUS: changes required ⚠️
> Code reviewer: Maria Reyes. Find me on slack like @majo

Even though I had no **errors** in the validator as requested by the Microverse requirements, I added some **unnecesary** headings to fix those _warnings_. No more warnings on the validator.

**Comment by majovanilla** [comment]
Thanks for the input about the warnings @alvp01  I will point this out to the team!!

And I understand that it makes no sense to add fake titles, that's why I would consider using different tags if we are not going to have a heading.

### Your project is approved!!

**Comment by alvp01** [comment]
> Thanks for the input about the warnings @alvp01 I will point this out to the team!!
> 
> And I understand that it makes no sense to add fake titles, that's why I would consider using different tags if we are not going to have a heading.
> 
> ### Your project is approved!!

Thanks for your time and work.

**Pull request merged**
